classic: false
# Possible values: permission, user, group, size, size_value, date, name, inode
blocks:
  - permission
  - user
#  - group
  - size
  - date
  - name

color:
  when: auto
  theme: custom

date: '+%y-%m-%d %H:%M'
dereference: false
icons:
  when: never

# ignore-globs:
#   - .git

indicators: false

layout: grid

recursion:
  enabled: false

size: short

permission: rwx

sorting:
  column: name
  reverse: false
  dir-grouping: first

no-symlink: false

total-size: false
hyperlink: never
symlink-arrow: ⇒
header: false
